name: Build Tauri App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          
      - name: Setup pnpm
        run: npm install -g pnpm
        working-directory: tauri-dotnet-sidecar

      - name: Build React frontend
        run: pnpm install && pnpm run build
        working-directory: tauri-dotnet-sidecar/react

      - name: Install dependencies
        run: pnpm install
        working-directory: tauri-dotnet-sidecar

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Download sidecar
        run: |
          mkdir -p src-tauri/bin
          curl -L -o src-tauri/bin/server.exe https://github.com/KaustubhIngale1704/dotnet-sidecar/releases/latest/download/server.exe

      - name: Prepare sidecar for Linux
        run: |
          cd src-tauri/bin
          cp server.exe server-x86_64-unknown-linux-gnu

      - name: Build Tauri App
        run: pnpm run tauri build
        working-directory: tauri-dotnet-sidecar/src-tauri
