name: 'publish-windows'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    runs-on: windows-latest
    permissions:
      contents: write
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: tauri-dotnet-sidecar

      - name: Download .NET sidecar
        run: |
          New-Item -ItemType Directory -Force -Path tauri-dotnet-sidecar/src-tauri/bin
          Invoke-WebRequest -Uri "https://github.com/KaustubhIngale1704/dotnet-sidecar/releases/latest/download/server.exe" -OutFile "tauri-dotnet-sidecar/src-tauri/bin/server.exe"

      - name: Prepare Windows sidecar
        run: |
          Copy-Item "tauri-dotnet-sidecar/src-tauri/bin/server.exe" "tauri-dotnet-sidecar/src-tauri/bin/server-x86_64-pc-windows-msvc.exe"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ''
